apiVersion: 1

deleteDatasources:
  - name: Jaeger
    orgId: 1
  - name: Loki
    orgId: 1

datasources:
- name: Loki
  type: loki
  uid: loki
  access: proxy
  url: http://loki:3100
  isDefault: true
  editable: true
- name: Jaeger
  type: jaeger
  access: proxy
  url: http://jaeger:16686
  isDefault: false
  editable: true
  jsonData:
    tracesToLogs:
      datasourceUid: loki
      tags:
        - appname
